version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - "gh-actions"
      - "dependencies"
    commit-message:
      prefix: "gh-actions"
      include: "scope"

  - package-ecosystem: nuget
    directory: /InitialState.NET
    schedule:
      interval: monthly
    labels:
      - "nuget"
      - "dependencies"
    commit-message:
      prefix: "nuget"
      include: "scope"
  
  # other supported packages can be found here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
